#ifndef GPUFANCTL_EXECUTION_ASSERTION_HPP_INCLUDED
#define GPUFANCTL_EXECUTION_ASSERTION_HPP_INCLUDED

#include "../assertion.hpp"

#define EXEC_CHECK GFC_CHECK

#endif // GPUFANCTL_EXECUTION_ASSERTION_HPP_INCLUDED
